# Generated by Django 2.0.4 on 2018-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField()),
                ('source', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
            ],
        ),
    ]
