# Generated by Django 2.0.4 on 2018-04-07 10:01

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='available_seats',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='status',
            name='booked_seats',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
