# Generated by Django 2.0.4 on 2018-04-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20180417_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.BusInfo'),
        ),
    ]
