# Generated by Django 2.0.4 on 2018-04-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_customer_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.BusInfo'),
        ),
    ]
