# Generated by Django 2.0.4 on 2018-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20180417_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='bus',
        ),
        migrations.AddField(
            model_name='status',
            name='bus_id',
            field=models.IntegerField(default=123),
        ),
    ]
