# Generated by Django 2.0.4 on 2018-04-25 11:15

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20180417_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='status',
            name='booked_seats',
        ),
        migrations.AddField(
            model_name='status',
            name='seats',
            field=models.CharField(default='a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
